# ETL3 Memory-Optimized Configuration File
# For memory-constrained systems (4-8GB RAM)

# S3 Configuration
s3:
  bucket: "healthcare-data-lake-prod"
  region: "us-east-1"
  prefix: "partitioned-data"
  compression: "zstd"
  encryption: "AES256"

# Processing Configuration - MEMORY OPTIMIZED
processing:
  chunk_size: 1000          # VERY small chunks for memory-constrained systems
  max_workers: 1            # Single worker to avoid memory multiplication
  memory_limit_mb: 1024     # Conservative 1GB limit
  enable_streaming: true

# Data Paths
data_paths:
  input_dir: "data"
  output_dir: "data/partitioned"
  fact_rate_path: "data/gold/fact_rate.parquet"
  
  dimensions:
    code: "data/dims/dim_code.parquet"
    code_cat: "data/dims/dim_code_cat.parquet"
    payer: "data/dims/dim_payer.parquet"
    provider_group: "data/dims/dim_provider_group.parquet"
    pos_set: "data/dims/dim_pos_set.parquet"
    npi: "data/dims/dim_npi.parquet"
    npi_address: "data/dims/dim_npi_address.parquet"
    npi_address_geo: "data/dims/dim_npi_address_geolocation.parquet"
  
  cross_references:
    pg_member_npi: "data/xrefs/xref_pg_member_npi.parquet"
    pg_member_tin: "data/xrefs/xref_pg_member_tin.parquet"

# Partitioning Configuration
partitioning:
  partition_columns:
    - "payer_slug"
    - "state"
    - "billing_class"
    - "procedure_set"
    - "procedure_class"
    - "primary_taxonomy_code"
    - "stat_area_name"
    - "year"
    - "month"
  
  # Partition size limits - MEMORY OPTIMIZED
  max_partition_size_mb: 50      # Smaller partitions
  min_partition_rows: 1
  max_partition_rows: 5000       # Smaller max partition size

# Athena Configuration
athena:
  database: "healthcare_data_lake"
  table: "fact_rate_enriched"
  output_location: "s3://healthcare-data-lake-prod/athena-results/"
  
  # Partition projection settings
  projection:
    payer_slug:
      type: "enum"
      values: ["unitedhealthcare-of-georgia-inc", "anthem-blue-cross-blue-shield"]
    state:
      type: "enum"
      values: ["GA", "FL", "CA", "TX", "NY", "IL", "PA", "OH", "NC", "MI"]
    billing_class:
      type: "enum"
      values: ["professional", "institutional"]
    year:
      type: "integer"
      range: "2020,2030"
    month:
      type: "integer"
      range: "1,12"

# Data Quality Configuration
data_quality:
  enable_validation: true
  sample_partitions: 5           # Reduced for memory efficiency
  max_errors_per_partition: 50   # Reduced for memory efficiency
  
  # Quality rules
  rules:
    required_fields:
      - "fact_uid"
      - "negotiated_rate"
      - "state"
      - "payer_slug"
    
    rate_validation:
      min_value: 0.01
      max_value: 1000000.0
    
    state_validation:
      valid_values: ["GA", "FL", "CA", "TX", "NY", "IL", "PA", "OH", "NC", "MI"]
    
    npi_validation:
      pattern: "^\\d{10}$"
    
    geocoding_validation:
      latitude_range: [-90, 90]
      longitude_range: [-180, 180]

# Monitoring Configuration
monitoring:
  enable_cloudwatch: false       # Disabled for memory efficiency
  enable_dashboard: false        # Disabled for memory efficiency
  enable_alarms: false           # Disabled for memory efficiency
  
  # CloudWatch settings
  namespace: "HealthcareDataLake/ETL3"
  
  # Alarms
  alarms:
    high_error_rate:
      threshold: 10
      evaluation_periods: 1
    
    low_processing_rate:
      threshold: 100
      evaluation_periods: 2
    
    high_memory_usage:
      threshold: 80
      evaluation_periods: 1

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log files
  log_dir: "logs"
  max_file_size_mb: 50           # Smaller log files
  backup_count: 3                # Fewer backups

# Security Configuration
security:
  enable_s3_encryption: true
  enable_versioning: true
  block_public_access: true
  
  # IAM permissions required
  required_permissions:
    - "s3:GetObject"
    - "s3:PutObject"
    - "s3:DeleteObject"
    - "s3:ListBucket"
    - "athena:StartQueryExecution"
    - "athena:GetQueryExecution"
    - "glue:CreateCrawler"
    - "glue:StartCrawler"
    - "cloudwatch:PutMetricData"
    - "cloudwatch:PutDashboard"

# Performance Tuning - MEMORY OPTIMIZED
performance:
  # S3 settings
  s3:
    max_pool_connections: 10     # Reduced for memory efficiency
    retry_attempts: 3
    timeout_seconds: 30
  
  # Polars settings
  polars:
    streaming: true
    lazy_evaluation: true
    memory_efficient: true
  
  # Parallel processing - DISABLED for memory efficiency
  parallel:
    max_workers: 1               # Single worker
    chunk_size: 1000             # Small chunks
    enable_multiprocessing: false # Disabled

# Environment-specific overrides
environments:
  development:
    s3:
      bucket: "healthcare-data-lake-dev"
    processing:
      chunk_size: 500            # Even smaller for development
      memory_limit_mb: 512       # Very conservative
    monitoring:
      enable_alarms: false
  
  staging:
    s3:
      bucket: "healthcare-data-lake-staging"
    processing:
      chunk_size: 1000           # Small chunks
      memory_limit_mb: 1024      # Conservative
    monitoring:
      enable_alarms: false       # Disabled for memory efficiency
  
  production:
    s3:
      bucket: "healthcare-data-lake-prod"
    processing:
      chunk_size: 1000           # Small chunks for memory-constrained systems
      memory_limit_mb: 1024      # Conservative limit
    monitoring:
      enable_alarms: false       # Disabled for memory efficiency
      enable_dashboard: false
